-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-exported.lua"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = "#f38ba8" })
hi(0, "@attribute", { fg = "#fae3b0" })
hi(0, "@character", { fg = "#f38ba8" })
hi(0, "@comment", { fg = "#4e4d5d" })
hi(0, "@comment.danger", { bg = "#f38ba8", fg = "#252434" })
hi(0, "@comment.note", { bg = "#89b4fa", fg = "#1e1d2d" })
hi(0, "@comment.todo", { bg = "#d9e0ee", fg = "#474656" })
hi(0, "@comment.warning", { bg = "#f8bd96", fg = "#252434" })
hi(0, "@constant", { fg = "#f8bd96" })
hi(0, "@constant.builtin", { fg = "#f8bd96" })
hi(0, "@constant.macro", { fg = "#f38ba8" })
hi(0, "@constructor", { fg = "#89dceb" })
hi(0, "@definition", { sp = "#414050", underline = true })
hi(0, "@diff.delta", { fg = "#605f6f" })
hi(0, "@diff.minus", { fg = "#f38ba8" })
hi(0, "@diff.plus", { fg = "#abe9b3" })
hi(0, "@error", { fg = "#f38ba8" })
hi(0, "@function", { fg = "#89b4fa" })
hi(0, "@function.builtin", { fg = "#89b4fa" })
hi(0, "@function.call", { fg = "#89b4fa" })
hi(0, "@function.macro", { fg = "#f38ba8" })
hi(0, "@function.method", { fg = "#89b4fa" })
hi(0, "@function.method.call", { fg = "#89b4fa" })
hi(0, "@ibl.indent.char.1", { fg = "#383747" })
hi(0, "@ibl.scope.char.1", { fg = "#fae3b0", nocombine = true })
hi(0, "@ibl.scope.char.2", { fg = "#d0a9e5", nocombine = true })
hi(0, "@ibl.scope.char.3", { fg = "#89b4fa", nocombine = true })
hi(0, "@ibl.scope.char.4", { fg = "#f8bd96", nocombine = true })
hi(0, "@ibl.scope.char.5", { fg = "#abe9b3", nocombine = true })
hi(0, "@ibl.scope.char.6", { fg = "#89dceb", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#fae3b0", underline = true })
hi(0, "@ibl.scope.underline.2", { sp = "#d0a9e5", underline = true })
hi(0, "@ibl.scope.underline.3", { sp = "#89b4fa", underline = true })
hi(0, "@ibl.scope.underline.4", { sp = "#f8bd96", underline = true })
hi(0, "@ibl.scope.underline.5", { sp = "#abe9b3", underline = true })
hi(0, "@ibl.scope.underline.6", { sp = "#89dceb", underline = true })
hi(0, "@ibl.scope.underline.7", { bg = "#252434" })
hi(0, "@ibl.whitespace.char.1", { fg = "#383747" })
hi(0, "@keyword", { fg = "#cba6f7" })
hi(0, "@keyword.conditional", { fg = "#cba6f7" })
hi(0, "@keyword.conditional.ternary", { fg = "#cba6f7" })
hi(0, "@keyword.directive", { fg = "#fae3b0" })
hi(0, "@keyword.directive.define", { fg = "#cba6f7" })
hi(0, "@keyword.exception", { fg = "#cba6f7" })
hi(0, "@keyword.function", { fg = "#cba6f7" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#cba6f7" })
hi(0, "@keyword.repeat", { fg = "#cba6f7" })
hi(0, "@keyword.return", { fg = "#cba6f7" })
hi(0, "@keyword.storage", { fg = "#fae3b0" })
hi(0, "@lsp.mod.readonly", { italic = true })
hi(0, "@lsp.type.concept", { fg = "#f8bd96" })
hi(0, "@lsp.type.modifier", { fg = "#d0a9e5" })
hi(0, "@markup.heading", { fg = "#89b4fa" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#1e1d2d", fg = "#1e1d2d", nocombine = true, sp = "#bfc6d4", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#1e1d2d", fg = "#1e1d2d", nocombine = true, sp = "#bfc6d4", underline = true })
hi(0, "@markup.link", { fg = "#f38ba8" })
hi(0, "@markup.link.label", { fg = "#89dceb" })
hi(0, "@markup.link.url", { fg = "#f8bd96", underline = true })
hi(0, "@markup.list", { fg = "#f38ba8" })
hi(0, "@markup.quote", { bg = "#252434" })
hi(0, "@markup.raw", { fg = "#f8bd96" })
hi(0, "@module", { fg = "#c7d1ff", italic = true })
hi(0, "@number", { fg = "#f8bd96" })
hi(0, "@number.float", { fg = "#f8bd96" })
hi(0, "@operator", { fg = "#89dceb" })
hi(0, "@property", { fg = "#b5e8e0" })
hi(0, "@punctuation.bracket", { fg = "#f38ba8" })
hi(0, "@punctuation.delimiter", { fg = "#605f6f" })
hi(0, "@reference", { fg = "#bfc6d4" })
hi(0, "@scope", { bold = true })
hi(0, "@string", { fg = "#abe9b3" })
hi(0, "@string.escape", { fg = "#89dceb" })
hi(0, "@string.regex", { fg = "#89dceb" })
hi(0, "@symbol", { fg = "#abe9b3" })
hi(0, "@tag", { fg = "#fae3b0" })
hi(0, "@tag.attribute", { fg = "#f38ba8" })
hi(0, "@tag.delimiter", { fg = "#f38ba8" })
hi(0, "@text", { fg = "#bfc6d4" })
hi(0, "@text.emphasis", { fg = "#f8bd96" })
hi(0, "@text.strike", { fg = "#f38ba8", strikethrough = true })
hi(0, "@type.builtin", { fg = "#fae3b0" })
hi(0, "@variable", { fg = "#c7d1ff" })
hi(0, "@variable.builtin", { fg = "#d0a9e5" })
hi(0, "@variable.member", { fg = "#f38ba8" })
hi(0, "@variable.member.key", { fg = "#f38ba8" })
hi(0, "@variable.parameter", { fg = "#f38ba8" })
hi(0, "Added", { fg = "#abe9b3" })
hi(0, "BlinkCmpDoc", { bg = "#1e1d2d" })
hi(0, "BlinkCmpDocBorder", { fg = "#4e4d5d" })
hi(0, "BlinkCmpDocCursorLine", { bg = "#2d2c3c" })
hi(0, "BlinkCmpDocSeparator", { fg = "#474656" })
hi(0, "BlinkCmpGhostText", { fg = "#4e4d5d" })
hi(0, "BlinkCmpKindClass", { fg = "#b5e8e0" })
hi(0, "BlinkCmpKindCodeium", { fg = "#b6f4be" })
hi(0, "BlinkCmpKindColor", { fg = "#d9e0ee" })
hi(0, "BlinkCmpKindConstant", { fg = "#f8bd96" })
hi(0, "BlinkCmpKindConstructor", { fg = "#89b4fa" })
hi(0, "BlinkCmpKindCopilot", { fg = "#abe9b3" })
hi(0, "BlinkCmpKindEnum", { fg = "#89b4fa" })
hi(0, "BlinkCmpKindEnumMember", { fg = "#d0a9e5" })
hi(0, "BlinkCmpKindEvent", { fg = "#fae3b0" })
hi(0, "BlinkCmpKindField", { fg = "#f38ba8" })
hi(0, "BlinkCmpKindFile", { fg = "#d9e0ee" })
hi(0, "BlinkCmpKindFolder", { fg = "#d9e0ee" })
hi(0, "BlinkCmpKindFunction", { fg = "#89b4fa" })
hi(0, "BlinkCmpKindIdentifier", { fg = "#f38ba8" })
hi(0, "BlinkCmpKindInterface", { fg = "#abe9b3" })
hi(0, "BlinkCmpKindKeyword", { fg = "#d9e0ee" })
hi(0, "BlinkCmpKindMethod", { fg = "#89b4fa" })
hi(0, "BlinkCmpKindModule", { fg = "#fae3b0" })
hi(0, "BlinkCmpKindOperator", { fg = "#bfc6d4" })
hi(0, "BlinkCmpKindProperty", { fg = "#f38ba8" })
hi(0, "BlinkCmpKindReference", { fg = "#bfc6d4" })
hi(0, "BlinkCmpKindSnippet", { fg = "#f38ba8" })
hi(0, "BlinkCmpKindStruct", { fg = "#cba6f7" })
hi(0, "BlinkCmpKindStructure", { fg = "#cba6f7" })
hi(0, "BlinkCmpKindSuperMaven", { fg = "#fae3b0" })
hi(0, "BlinkCmpKindTabNine", { fg = "#ffa5c3" })
hi(0, "BlinkCmpKindText", { fg = "#abe9b3" })
hi(0, "BlinkCmpKindType", { fg = "#fae3b0" })
hi(0, "BlinkCmpKindTypeParameter", { fg = "#f38ba8" })
hi(0, "BlinkCmpKindUnit", { fg = "#cba6f7" })
hi(0, "BlinkCmpKindValue", { fg = "#89dceb" })
hi(0, "BlinkCmpKindVariable", { fg = "#cba6f7" })
hi(0, "BlinkCmpLabel", { fg = "#d9e0ee" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#f38ba8", strikethrough = true })
hi(0, "BlinkCmpLabelDescription", { fg = "#605f6f" })
hi(0, "BlinkCmpLabelDetail", { fg = "#605f6f" })
hi(0, "BlinkCmpLabelMatch", { bold = true, fg = "#89b4fa" })
hi(0, "BlinkCmpMenu", { bg = "#1e1d2d" })
hi(0, "BlinkCmpMenuBorder", { fg = "#4e4d5d" })
hi(0, "BlinkCmpMenuSelection", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "BlinkCmpScrollBarGutter", { bg = "#252434" })
hi(0, "BlinkCmpScrollBarThumb", { bg = "#474656" })
hi(0, "BlinkCmpSignatureHelp", { bg = "#1e1d2d" })
hi(0, "BlinkCmpSignatureHelpActiveParameter", { bold = true, fg = "#89b4fa" })
hi(0, "BlinkCmpSignatureHelpBorder", { fg = "#4e4d5d" })
hi(0, "BlinkCmpSource", { fg = "#4e4d5d" })
hi(0, "Boolean", { fg = "#f8bd96" })
hi(0, "Changed", { fg = "#fae3b0" })
hi(0, "Character", { fg = "#f38ba8" })
hi(0, "CmpBorder", { fg = "#4e4d5d" })
hi(0, "CmpDoc", { bg = "#1e1d2d" })
hi(0, "CmpDocBorder", { fg = "#4e4d5d" })
hi(0, "CmpItemAbbr", { fg = "#d9e0ee" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#605f6f" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#89b4fa" })
hi(0, "CmpItemKindClass", { fg = "#b5e8e0" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindClassIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindCodeium", { fg = "#b6f4be" })
hi(0, "CmpItemKindColor", { fg = "#d9e0ee" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindConstant", { fg = "#f8bd96" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindConstructor", { fg = "#89b4fa" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindCopilot", { fg = "#abe9b3" })
hi(0, "CmpItemKindDefault", { fg = "#89dceb" })
hi(0, "CmpItemKindEnum", { fg = "#89b4fa" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindEnumMember", { fg = "#d0a9e5" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindEvent", { fg = "#fae3b0" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindField", { fg = "#f38ba8" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFile", { fg = "#d9e0ee" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFolder", { fg = "#d9e0ee" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFunction", { fg = "#89b4fa" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindIconDefault", { fg = "#89dceb" })
hi(0, "CmpItemKindIdentifier", { fg = "#f38ba8" })
hi(0, "CmpItemKindInterface", { fg = "#abe9b3" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindKeyword", { fg = "#d9e0ee" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindMethod", { fg = "#89b4fa" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindMinuet", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#fae3b0" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindOperator", { fg = "#bfc6d4" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindProperty", { fg = "#f38ba8" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindReference", { fg = "#bfc6d4" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindSnippet", { fg = "#f38ba8" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindStruct", { fg = "#cba6f7" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindStructure", { fg = "#cba6f7" })
hi(0, "CmpItemKindSuperMaven", { fg = "#fae3b0" })
hi(0, "CmpItemKindTabNine", { fg = "#ffa5c3" })
hi(0, "CmpItemKindText", { fg = "#abe9b3" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindType", { fg = "#fae3b0" })
hi(0, "CmpItemKindTypeParameter", { fg = "#f38ba8" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindUnit", { fg = "#cba6f7" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindValue", { fg = "#89dceb" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindVariable", { fg = "#cba6f7" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpPmenu", { bg = "#1e1d2d" })
hi(0, "CmpSel", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "ColorColumn", { bg = "#252434" })
hi(0, "Comment", { fg = "#605f6f" })
hi(0, "CompileModeCheckResult", { bold = true, fg = "#ff9966" })
hi(0, "CompileModeCheckTarget", { fg = "#ff9966" })
hi(0, "CompileModeCommandOutput", { fg = "#6699ff" })
hi(0, "CompileModeDirectoryMessage", { fg = "#6699ff" })
hi(0, "CompileModeError", { fg = "#ff0000" })
hi(0, "CompileModeInfo", { fg = "#008000" })
hi(0, "CompileModeMessage", { underline = true })
hi(0, "CompileModeMessageCol", { fg = "#00ffff" })
hi(0, "CompileModeMessageRow", { fg = "#ff00ff" })
hi(0, "CompileModeOutputFile", { fg = "#9966cc" })
hi(0, "CompileModeWarning", { fg = "#bbbb00" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#cba6f7" })
hi(0, "Constant", { fg = "#f8bd96" })
hi(0, "Cursor", { bg = "#bfc6d4", fg = "#1e1d2d" })
hi(0, "CursorColumn", { bg = "#282737" })
hi(0, "CursorLine", { bg = "#252434" })
hi(0, "CursorLineNr", { fg = "#d9e0ee" })
hi(0, "Debug", { fg = "#f38ba8" })
hi(0, "Define", { fg = "#cba6f7" })
hi(0, "Delimiter", { fg = "#f38ba8" })
hi(0, "DiagnosticError", { fg = "#f38ba8" })
hi(0, "DiagnosticHint", { fg = "#d0a9e5" })
hi(0, "DiagnosticInfo", { fg = "#abe9b3" })
hi(0, "DiagnosticWarn", { fg = "#fae3b0" })
hi(0, "DiffAdd", { bg = "#2c313a", fg = "#abe9b3" })
hi(0, "DiffAdded", { bg = "#2c313a", fg = "#abe9b3" })
hi(0, "DiffChange", { bg = "#242333", fg = "#605f6f" })
hi(0, "DiffChangeDelete", { bg = "#332839", fg = "#f38ba8" })
hi(0, "DiffDelete", { bg = "#332839", fg = "#f38ba8" })
hi(0, "DiffModified", { bg = "#332d37", fg = "#f8bd96" })
hi(0, "DiffRemoved", { bg = "#332839", fg = "#f38ba8" })
hi(0, "DiffText", { bg = "#252434", fg = "#d9e0ee" })
hi(0, "Directory", { fg = "#89b4fa" })
hi(0, "Error", { bg = "#f38ba8", fg = "#1e1d2d" })
hi(0, "ErrorMsg", { bg = "#1e1d2d", fg = "#f38ba8" })
hi(0, "Exception", { fg = "#f38ba8" })
hi(0, "Float", { fg = "#f8bd96" })
hi(0, "FloatBorder", { fg = "#89b4fa" })
hi(0, "FloatTitle", { bg = "#474656", fg = "#d9e0ee" })
hi(0, "FoldColumn", {})
hi(0, "Folded", { bg = "#252434", fg = "#605f6f" })
hi(0, "Function", { fg = "#89b4fa" })
hi(0, "IblChar", { fg = "#383747" })
hi(0, "IblIndent", { link = "NonText" })
hi(0, "IblScope", { fg = "#4f5258" })
hi(0, "IblScopeChar", { fg = "#474656" })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "Identifier", { fg = "#f38ba8" })
hi(0, "IncSearch", { bg = "#f8bd96", fg = "#282737" })
hi(0, "Include", { fg = "#f5c2e7" })
hi(0, "Keyword", { fg = "#cba6f7" })
hi(0, "Label", { fg = "#fae3b0" })
hi(0, "LazyButton", { bg = "#2d2c3c", fg = "#77768a" })
hi(0, "LazyCommit", { fg = "#abe9b3" })
hi(0, "LazyCommitIssue", { fg = "#f5c2e7" })
hi(0, "LazyDir", { fg = "#bfc6d4" })
hi(0, "LazyH1", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "LazyH2", { bold = true, fg = "#f38ba8", underline = true })
hi(0, "LazyNoCond", { fg = "#f38ba8" })
hi(0, "LazyOperator", { fg = "#d9e0ee" })
hi(0, "LazyProgressDone", { fg = "#abe9b3" })
hi(0, "LazyReasonCmd", { fg = "#ffe9b6" })
hi(0, "LazyReasonEvent", { fg = "#fae3b0" })
hi(0, "LazyReasonFt", { fg = "#d0a9e5" })
hi(0, "LazyReasonImport", { fg = "#d9e0ee" })
hi(0, "LazyReasonKeys", { fg = "#b5e8e0" })
hi(0, "LazyReasonPlugin", { fg = "#f38ba8" })
hi(0, "LazyReasonRuntime", { fg = "#8bc2f0" })
hi(0, "LazyReasonSource", { fg = "#89dceb" })
hi(0, "LazyReasonStart", { fg = "#d9e0ee" })
hi(0, "LazySpecial", { fg = "#89b4fa" })
hi(0, "LazyTaskOutput", { fg = "#d9e0ee" })
hi(0, "LazyUrl", { fg = "#bfc6d4" })
hi(0, "LazyValue", { fg = "#b5e8e0" })
hi(0, "LineNr", { fg = "#474656" })
hi(0, "LspInlayHint", { bg = "#242434", fg = "#605f6f" })
hi(0, "LspKindMinuet", { link = "LspKindText" })
hi(0, "LspReferenceRead", { bg = "#3e3d4d" })
hi(0, "LspReferenceText", { bg = "#3e3d4d" })
hi(0, "LspReferenceWrite", { bg = "#3e3d4d" })
hi(0, "LspSignatureActiveParameter", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "Macro", { fg = "#f38ba8" })
hi(0, "MasonHeader", { bg = "#f38ba8", fg = "#1e1d2d" })
hi(0, "MasonHeaderSecondary", { link = "MasonHighlightBlock" })
hi(0, "MasonHighlight", { fg = "#89b4fa" })
hi(0, "MasonHighlightBlock", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHighlightBlock" })
hi(0, "MasonMuted", { fg = "#605f6f" })
hi(0, "MasonMutedBlock", { bg = "#2d2c3c", fg = "#605f6f" })
hi(0, "MatchParen", { link = "MatchWord" })
hi(0, "MatchWord", { bg = "#474656", fg = "#d9e0ee" })
hi(0, "MinuetDuetAdd", { link = "DiffAdd" })
hi(0, "MinuetDuetComment", { link = "Comment" })
hi(0, "MinuetDuetCursor", { link = "IncSearch" })
hi(0, "MinuetDuetDelete", { link = "DiffDelete" })
hi(0, "MinuetVirtualText", { link = "Comment" })
hi(0, "ModeMsg", { fg = "#abe9b3" })
hi(0, "MoreMsg", { fg = "#abe9b3" })
hi(0, "MultiCursorCursor", { reverse = true })
hi(0, "MultiCursorDisabledCursor", { reverse = true })
hi(0, "MultiCursorMainSign", { fg = "#383747" })
hi(0, "NonText", { fg = "#383747" })
hi(0, "Normal", { bg = "#1e1d2d", fg = "#bfc6d4" })
hi(0, "NormalFloat", { bg = "#191828" })
hi(0, "Number", { fg = "#f8bd96" })
hi(0, "NvChAsciiHeader", { fg = "#89b4fa" })
hi(0, "NvChHeadbaby_pink", { bg = "#ffa5c3", fg = "#1e1d2d" })
hi(0, "NvChHeadblue", { bg = "#89b4fa", fg = "#1e1d2d" })
hi(0, "NvChHeadcyan", { bg = "#89dceb", fg = "#1e1d2d" })
hi(0, "NvChHeadgreen", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "NvChHeading", { bg = "#89b4fa", bold = true, fg = "#1e1d2d" })
hi(0, "NvChHeadorange", { bg = "#f8bd96", fg = "#1e1d2d" })
hi(0, "NvChHeadpurple", { bg = "#d0a9e5", fg = "#1e1d2d" })
hi(0, "NvChHeadred", { bg = "#f38ba8", fg = "#1e1d2d" })
hi(0, "NvChHeadteal", { bg = "#b5e8e0", fg = "#1e1d2d" })
hi(0, "NvChHeadvibrant_green", { bg = "#b6f4be", fg = "#1e1d2d" })
hi(0, "NvChHeadwhite", { bg = "#d9e0ee", fg = "#1e1d2d" })
hi(0, "NvChHeadyellow", { bg = "#fae3b0", fg = "#1e1d2d" })
hi(0, "NvChSection", { bg = "#252434" })
hi(0, "NvDashAscii", { fg = "#89b4fa" })
hi(0, "NvDashButtons", { fg = "#605f6f" })
hi(0, "NvDashFooter", { fg = "#f38ba8" })
hi(0, "NvimInternalError", { fg = "#f38ba8" })
hi(0, "NvimTreeCursorLine", { bg = "#1e1d2d" })
hi(0, "NvimTreeDiagnosticErrorFileHL", { link = "DiagnosticError" })
hi(0, "NvimTreeDiagnosticErrorFolderHL", { link = "DiagnosticError" })
hi(0, "NvimTreeDiagnosticHintFileHL", { link = "DiagnosticHint" })
hi(0, "NvimTreeDiagnosticHintFolderHL", { link = "DiagnosticHint" })
hi(0, "NvimTreeDiagnosticInfoFileHL", { link = "DiagnosticNormal" })
hi(0, "NvimTreeDiagnosticInfoFolderHL", { link = "DiagnosticNormal" })
hi(0, "NvimTreeDiagnosticWarnFileHL", { link = "DiagnosticWarn" })
hi(0, "NvimTreeDiagnosticWarnFolderHL", { link = "DiagnosticWarn" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#89b4fa" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#191828" })
hi(0, "NvimTreeFolderArrowClosed", { fg = "#4e4d5d" })
hi(0, "NvimTreeFolderArrowOpen", { fg = "#89b4fa" })
hi(0, "NvimTreeFolderIcon", { fg = "#89b4fa" })
hi(0, "NvimTreeFolderName", { fg = "#89b4fa" })
hi(0, "NvimTreeGitDeleted", { fg = "#f38ba8" })
hi(0, "NvimTreeGitDirty", { fg = "#f38ba8" })
hi(0, "NvimTreeGitIgnored", { fg = "#605f6f" })
hi(0, "NvimTreeGitNew", { fg = "#fae3b0" })
hi(0, "NvimTreeIndentMarker", { fg = "#333241" })
hi(0, "NvimTreeNormal", { bg = "#191828" })
hi(0, "NvimTreeNormalNC", { bg = "#191828" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#89b4fa" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#f38ba8" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#fae3b0" })
hi(0, "NvimTreeWinSeparator", { bg = "#191828", fg = "#191828" })
hi(0, "NvimTreeWindowPicker", { bg = "#252434", fg = "#f38ba8" })
hi(0, "Operator", { fg = "#bfc6d4" })
hi(0, "Pmenu", { bg = "#2d2c3c" })
hi(0, "PmenuSbar", { bg = "#2d2c3c" })
hi(0, "PmenuSel", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "PmenuThumb", { bg = "#474656" })
hi(0, "PreProc", { fg = "#fae3b0" })
hi(0, "Question", { fg = "#89b4fa" })
hi(0, "QuickFixLine", { bg = "#282737" })
hi(0, "RainbowBlue", { fg = "#89b4fa" })
hi(0, "RainbowCyan", { fg = "#89dceb" })
hi(0, "RainbowDelimiterBlue", { ctermfg = 12, fg = "#458588" })
hi(0, "RainbowDelimiterCyan", { ctermfg = 14, fg = "#a89984" })
hi(0, "RainbowDelimiterGreen", { ctermfg = 10, fg = "#689d6a" })
hi(0, "RainbowDelimiterOrange", { ctermfg = 15, fg = "#d65d0e" })
hi(0, "RainbowDelimiterRed", { ctermfg = 9, fg = "#cc241d" })
hi(0, "RainbowDelimiterViolet", { ctermfg = 13, fg = "#b16286" })
hi(0, "RainbowDelimiterYellow", { ctermfg = 11, fg = "#d79921" })
hi(0, "RainbowGreen", { fg = "#abe9b3" })
hi(0, "RainbowOrange", { fg = "#f8bd96" })
hi(0, "RainbowRed", { fg = "#f38ba8" })
hi(0, "RainbowViolet", { fg = "#d0a9e5" })
hi(0, "RainbowYellow", { fg = "#fae3b0" })
hi(0, "Removed", { fg = "#f38ba8" })
hi(0, "Repeat", { fg = "#fae3b0" })
hi(0, "Search", { bg = "#fae3b0", fg = "#282737" })
hi(0, "SignColumn", { fg = "#383747" })
hi(0, "Special", { fg = "#89dceb" })
hi(0, "SpecialChar", { fg = "#f38ba8" })
hi(0, "SpecialKey", { fg = "#383747" })
hi(0, "St_CommandMode", { bg = "#abe9b3", bold = true, fg = "#1e1d2d" })
hi(0, "St_CommandModeSep", { bg = "#474656", fg = "#abe9b3" })
hi(0, "St_ConfirmMode", { bg = "#b5e8e0", bold = true, fg = "#1e1d2d" })
hi(0, "St_ConfirmModeSep", { bg = "#474656", fg = "#b5e8e0" })
hi(0, "St_EmptySpace", { bg = "#2f2e3e", fg = "#474656" })
hi(0, "St_InsertMode", { bg = "#c7a0dc", bold = true, fg = "#1e1d2d" })
hi(0, "St_InsertModeSep", { bg = "#474656", fg = "#c7a0dc" })
hi(0, "St_Lsp", { bg = "#252434", fg = "#8bc2f0" })
hi(0, "St_LspHints", { bg = "#252434", fg = "#d0a9e5" })
hi(0, "St_LspInfo", { bg = "#252434", fg = "#abe9b3" })
hi(0, "St_LspMsg", { bg = "#252434", fg = "#abe9b3" })
hi(0, "St_NTerminalMode", { bg = "#fae3b0", bold = true, fg = "#1e1d2d" })
hi(0, "St_NTerminalModeSep", { bg = "#474656", fg = "#fae3b0" })
hi(0, "St_NormalMode", { bg = "#8bc2f0", bold = true, fg = "#1e1d2d" })
hi(0, "St_NormalModeSep", { bg = "#474656", fg = "#8bc2f0" })
hi(0, "St_ReplaceMode", { bg = "#f8bd96", bold = true, fg = "#1e1d2d" })
hi(0, "St_ReplaceModeSep", { bg = "#474656", fg = "#f8bd96" })
hi(0, "St_SelectMode", { bg = "#89b4fa", bold = true, fg = "#1e1d2d" })
hi(0, "St_SelectModeSep", { bg = "#474656", fg = "#89b4fa" })
hi(0, "St_TerminalMode", { bg = "#abe9b3", bold = true, fg = "#1e1d2d" })
hi(0, "St_TerminalModeSep", { bg = "#474656", fg = "#abe9b3" })
hi(0, "St_VisualMode", { bg = "#89dceb", bold = true, fg = "#1e1d2d" })
hi(0, "St_VisualModeSep", { bg = "#474656", fg = "#89dceb" })
hi(0, "St_cwd_icon", { bg = "#f38ba8", fg = "#2d2c3c" })
hi(0, "St_cwd_sep", { bg = "#252434", fg = "#f38ba8" })
hi(0, "St_cwd_text", { bg = "#2f2e3e", fg = "#d9e0ee" })
hi(0, "St_file", { bg = "#2f2e3e", fg = "#d9e0ee" })
hi(0, "St_file_sep", { bg = "#252434", fg = "#2f2e3e" })
hi(0, "St_gitIcons", { bg = "#252434", bold = true, fg = "#737184" })
hi(0, "St_lspError", { bg = "#252434", fg = "#f38ba8" })
hi(0, "St_lspWarning", { bg = "#252434", fg = "#fae3b0" })
hi(0, "St_pos_icon", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "St_pos_sep", { bg = "#2f2e3e", fg = "#abe9b3" })
hi(0, "St_pos_text", { bg = "#2f2e3e", fg = "#abe9b3" })
hi(0, "Statement", { fg = "#f38ba8" })
hi(0, "StatusLine", { bg = "#252434" })
hi(0, "StorageClass", { fg = "#fae3b0" })
hi(0, "String", { fg = "#abe9b3" })
hi(0, "Structure", { fg = "#cba6f7" })
hi(0, "Substitute", { bg = "#fae3b0", fg = "#282737" })
hi(0, "TBTabTitle", { bg = "#89b4fa", fg = "#1e1d2d" })
hi(0, "TabLine", { bg = "#252434" })
hi(0, "Tag", { fg = "#fae3b0" })
hi(0, "TbBufOff", { bg = "#252434", fg = "#605f6f" })
hi(0, "TbBufOffClose", { bg = "#252434", fg = "#605f6f" })
hi(0, "TbBufOffModified", { bg = "#252434", fg = "#f38ba8" })
hi(0, "TbBufOn", { bg = "#1e1d2d", fg = "#d9e0ee" })
hi(0, "TbBufOnClose", { bg = "#1e1d2d", fg = "#f38ba8" })
hi(0, "TbBufOnModified", { bg = "#1e1d2d", fg = "#abe9b3" })
hi(0, "TbCloseAllBufsBtn", { bg = "#f38ba8", bold = true, fg = "#1e1d2d" })
hi(0, "TbFill", { bg = "#252434" })
hi(0, "TbTabCloseBtn", { bg = "#8bc2f0", fg = "#1e1d2d" })
hi(0, "TbTabNewBtn", { bg = "#363545", fg = "#d9e0ee" })
hi(0, "TbTabOff", { bg = "#252434", fg = "#d9e0ee" })
hi(0, "TbTabOn", { bg = "#1e1d2d", fg = "#f38ba8" })
hi(0, "TbThemeToggleBtn", { bg = "#3e3d4d", bold = true, fg = "#d9e0ee" })
hi(0, "TelescopeBorder", { bg = "#191828", fg = "#191828" })
hi(0, "TelescopeMatching", { bg = "#2d2c3c", fg = "#89b4fa" })
hi(0, "TelescopeNormal", { bg = "#191828" })
hi(0, "TelescopePreviewTitle", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "TelescopePromptBorder", { bg = "#252434", fg = "#252434" })
hi(0, "TelescopePromptNormal", { bg = "#252434", fg = "#d9e0ee" })
hi(0, "TelescopePromptPrefix", { bg = "#252434", fg = "#f38ba8" })
hi(0, "TelescopePromptTitle", { bg = "#f38ba8", fg = "#1e1d2d" })
hi(0, "TelescopeResultsDiffAdd", { fg = "#abe9b3" })
hi(0, "TelescopeResultsDiffChange", { fg = "#fae3b0" })
hi(0, "TelescopeResultsDiffDelete", { fg = "#f38ba8" })
hi(0, "TelescopeResultsTitle", { bg = "#191828", fg = "#191828" })
hi(0, "TelescopeSelection", { bg = "#252434", fg = "#d9e0ee" })
hi(0, "Title", { fg = "#89b4fa" })
hi(0, "Todo", { bg = "#282737", fg = "#fae3b0" })
hi(0, "TooLong", { fg = "#f38ba8" })
hi(0, "Type", { fg = "#fae3b0" })
hi(0, "Typedef", { fg = "#fae3b0" })
hi(0, "Variable", { fg = "#bfc6d4" })
hi(0, "Visual", { bg = "#2f2e3e" })
hi(0, "VisualNOS", { fg = "#f38ba8" })
hi(0, "WarningMsg", { fg = "#f38ba8" })
hi(0, "WhichKey", { fg = "#89b4fa" })
hi(0, "WhichKeyDesc", { fg = "#f38ba8" })
hi(0, "WhichKeyGroup", { fg = "#abe9b3" })
hi(0, "WhichKeySeparator", { fg = "#605f6f" })
hi(0, "WhichKeyValue", { fg = "#abe9b3" })
hi(0, "WildMenu", { bg = "#fae3b0", fg = "#f38ba8" })
hi(0, "WinBar", {})
hi(0, "WinBarNC", {})
hi(0, "WinSeparator", { fg = "#383747" })
hi(0, "diffNewFile", { fg = "#89b4fa" })
hi(0, "diffOldFile", { fg = "#ffa5c3" })
hi(0, "gitcommitBranch", { bold = true, fg = "#f8bd96" })
hi(0, "gitcommitComment", { fg = "#383747" })
hi(0, "gitcommitDiscarded", { fg = "#383747" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#f38ba8" })
hi(0, "gitcommitDiscardedType", { fg = "#89b4fa" })
hi(0, "gitcommitHeader", { fg = "#cba6f7" })
hi(0, "gitcommitOverflow", { fg = "#f38ba8" })
hi(0, "gitcommitSelected", { fg = "#383747" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#abe9b3" })
hi(0, "gitcommitSelectedType", { fg = "#89b4fa" })
hi(0, "gitcommitSummary", { fg = "#abe9b3" })
hi(0, "gitcommitUnmergedFile", { bold = true, fg = "#f38ba8" })
hi(0, "gitcommitUnmergedType", { fg = "#89b4fa" })
hi(0, "gitcommitUntracked", { fg = "#383747" })
hi(0, "gitcommitUntrackedFile", { fg = "#fae3b0" })
hi(0, "healthSuccess", { bg = "#abe9b3", fg = "#1e1d2d" })
hi(0, "lCursor", { bg = "#bfc6d4", fg = "#1e1d2d" })
hi(0, "vimLetVar", { link = "vimVar" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#282737"
g.terminal_color_1 = "#f38ba8"
g.terminal_color_2 = "#abe9b3"
g.terminal_color_3 = "#fae3b0"
g.terminal_color_4 = "#89b4fa"
g.terminal_color_5 = "#cba6f7"
g.terminal_color_6 = "#89dceb"
g.terminal_color_7 = "#bfc6d4"
g.terminal_color_8 = "#383747"
g.terminal_color_9 = "#f38ba8"
g.terminal_color_10 = "#abe9b3"
g.terminal_color_11 = "#fae3b0"
g.terminal_color_12 = "#89b4fa"
g.terminal_color_13 = "#cba6f7"
g.terminal_color_14 = "#89dceb"
g.terminal_color_15 = "#d9e0ee"
