-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd 'highlight clear'
end
vim.g.colors_name = 'onedark'

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, '@annotation', { fg = '#a7aab0' })
hi(0, '@attribute', { fg = '#51a8b3' })
hi(0, '@attribute.builtin', { link = 'Special' })
hi(0, '@attribute.typescript', { fg = '#57a5e5' })
hi(0, '@boolean', { fg = '#c49060' })
hi(0, '@character', { fg = '#c49060' })
hi(0, '@character.special', { link = 'SpecialChar' })
hi(0, '@comment', { fg = '#5a5b5e', italic = true })
hi(0, '@comment.error', { link = 'DiagnosticError' })
hi(0, '@comment.note', { link = 'DiagnosticInfo' })
hi(0, '@comment.todo', { fg = '#de5d68', italic = true })
hi(0, '@comment.todo.checked', { fg = '#8fb573', italic = true })
hi(0, '@comment.todo.unchecked', { fg = '#de5d68', italic = true })
hi(0, '@comment.warning', { link = 'DiagnosticWarn' })
hi(0, '@conditional', { fg = '#bb70d2' })
hi(0, '@constant', { fg = '#c49060' })
hi(0, '@constant.builtin', { fg = '#c49060' })
hi(0, '@constant.macro', { fg = '#c49060' })
hi(0, '@constructor', { bold = true, fg = '#dbb671' })
hi(0, '@danger', { fg = '#a7aab0' })
hi(0, '@diff.add', { fg = '#8fb573' })
hi(0, '@diff.delete', { fg = '#de5d68' })
hi(0, '@diff.delta', { fg = '#57a5e5' })
hi(0, '@diff.minus', { fg = '#de5d68' })
hi(0, '@diff.plus', { fg = '#8fb573' })
hi(0, '@error', { fg = '#a7aab0' })
hi(0, '@exception', { fg = '#bb70d2' })
hi(0, '@field', { fg = '#51a8b3' })
hi(0, '@float', { fg = '#c49060' })
hi(0, '@function', { fg = '#57a5e5' })
hi(0, '@function.builtin', { fg = '#51a8b3' })
hi(0, '@function.macro', { fg = '#51a8b3' })
hi(0, '@function.method', { fg = '#57a5e5' })
hi(0, '@include', { fg = '#bb70d2' })
hi(0, '@keyword', { fg = '#bb70d2' })
hi(0, '@keyword.conditional', { fg = '#bb70d2' })
hi(0, '@keyword.directive', { fg = '#bb70d2' })
hi(0, '@keyword.exception', { fg = '#bb70d2' })
hi(0, '@keyword.function', { fg = '#bb70d2' })
hi(0, '@keyword.import', { fg = '#bb70d2' })
hi(0, '@keyword.operator', { fg = '#bb70d2' })
hi(0, '@keyword.repeat', { fg = '#bb70d2' })
hi(0, '@label', { fg = '#de5d68' })
hi(0, '@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
hi(0, '@lsp.type.builtinType', { fg = '#c49060' })
hi(0, '@lsp.type.class', { link = '@type' })
hi(0, '@lsp.type.comment', { fg = '#5a5b5e', italic = true })
hi(0, '@lsp.type.decorator', { link = '@attribute' })
hi(0, '@lsp.type.enum', { fg = '#dbb671' })
hi(0, '@lsp.type.enumMember', { fg = '#c49060' })
hi(0, '@lsp.type.event', { link = '@type' })
hi(0, '@lsp.type.function', { link = '@function' })
hi(0, '@lsp.type.generic', { fg = '#a7aab0' })
hi(0, '@lsp.type.interface', { fg = '#dbb671' })
hi(0, '@lsp.type.keyword', { fg = '#bb70d2' })
hi(0, '@lsp.type.macro', { fg = '#51a8b3' })
hi(0, '@lsp.type.method', { fg = '#57a5e5' })
hi(0, '@lsp.type.modifier', { link = '@type.qualifier' })
hi(0, '@lsp.type.namespace', { fg = '#dbb671' })
hi(0, '@lsp.type.number', { fg = '#c49060' })
hi(0, '@lsp.type.operator', { link = '@operator' })
hi(0, '@lsp.type.parameter', { fg = '#de5d68' })
hi(0, '@lsp.type.property', { fg = '#51a8b3' })
hi(0, '@lsp.type.regexp', { link = '@string.regexp' })
hi(0, '@lsp.type.string', { link = '@string' })
hi(0, '@lsp.type.struct', { link = '@type' })
hi(0, '@lsp.type.type', { link = '@type' })
hi(0, '@lsp.type.typeParameter', { fg = '#dbb671' })
hi(0, '@lsp.type.variable', { fg = '#a7aab0' })
hi(0, '@lsp.typemod.function.defaultLibrary', { fg = '#57a5e5' })
hi(0, '@lsp.typemod.method.defaultLibrary', { fg = '#57a5e5' })
hi(0, '@lsp.typemod.operator.injected', { fg = '#a7aab0' })
hi(0, '@lsp.typemod.string.injected', { fg = '#8fb573' })
hi(0, '@lsp.typemod.variable.defaultLibrary', { fg = '#de5d68' })
hi(0, '@lsp.typemod.variable.injected', { fg = '#a7aab0' })
hi(0, '@lsp.typemod.variable.static', { fg = '#c49060' })
hi(0, '@markup.emphasis', { fg = '#a7aab0', italic = true })
hi(0, '@markup.environment', { fg = '#a7aab0' })
hi(0, '@markup.environment.name', { fg = '#a7aab0' })
hi(0, '@markup.heading', { bold = true, fg = '#c49060' })
hi(0, '@markup.heading.1.delimiter.vimdoc', { bg = '#232326', fg = '#232326', nocombine = true, sp = '#a7aab0', underdouble = true })
hi(0, '@markup.heading.1.markdown', { bold = true, fg = '#de5d68' })
hi(0, '@markup.heading.1.marker.markdown', { bold = true, fg = '#de5d68' })
hi(0, '@markup.heading.2.delimiter.vimdoc', { bg = '#232326', fg = '#232326', nocombine = true, sp = '#a7aab0', underline = true })
hi(0, '@markup.heading.2.markdown', { bold = true, fg = '#bb70d2' })
hi(0, '@markup.heading.2.marker.markdown', { bold = true, fg = '#bb70d2' })
hi(0, '@markup.heading.3.markdown', { bold = true, fg = '#c49060' })
hi(0, '@markup.heading.3.marker.markdown', { bold = true, fg = '#c49060' })
hi(0, '@markup.heading.4.markdown', { bold = true, fg = '#de5d68' })
hi(0, '@markup.heading.4.marker.markdown', { bold = true, fg = '#de5d68' })
hi(0, '@markup.heading.5.markdown', { bold = true, fg = '#bb70d2' })
hi(0, '@markup.heading.5.marker.markdown', { bold = true, fg = '#bb70d2' })
hi(0, '@markup.heading.6.markdown', { bold = true, fg = '#c49060' })
hi(0, '@markup.heading.6.marker.markdown', { bold = true, fg = '#c49060' })
hi(0, '@markup.link', { fg = '#57a5e5' })
hi(0, '@markup.link.url', { fg = '#51a8b3', underline = true })
hi(0, '@markup.list', { fg = '#de5d68' })
hi(0, '@markup.math', { fg = '#a7aab0' })
hi(0, '@markup.raw', { fg = '#8fb573' })
hi(0, '@markup.strike', { fg = '#a7aab0', strikethrough = true })
hi(0, '@markup.strong', { bold = true, fg = '#a7aab0' })
hi(0, '@markup.underline', { fg = '#a7aab0', underline = true })
hi(0, '@method', { fg = '#57a5e5' })
hi(0, '@module', { fg = '#dbb671' })
hi(0, '@module.builtin', { link = 'Special' })
hi(0, '@namespace', { fg = '#dbb671' })
hi(0, '@none', { fg = '#a7aab0' })
hi(0, '@note', { fg = '#a7aab0' })
hi(0, '@number', { fg = '#c49060' })
hi(0, '@number.float', { fg = '#c49060' })
hi(0, '@operator', { fg = '#a7aab0' })
hi(0, '@parameter', { fg = '#de5d68' })
hi(0, '@parameter.reference', { fg = '#a7aab0' })
hi(0, '@preproc', { fg = '#bb70d2' })
hi(0, '@property', { fg = '#51a8b3' })
hi(0, '@punctuation.bracket', { fg = '#818387' })
hi(0, '@punctuation.delimiter', { fg = '#818387' })
hi(0, '@punctuation.special', { fg = '#de5d68' })
hi(0, '@repeat', { fg = '#bb70d2' })
hi(0, '@string', { fg = '#8fb573' })
hi(0, '@string.escape', { fg = '#de5d68' })
hi(0, '@string.regex', { fg = '#c49060' })
hi(0, '@string.regexp', { fg = '#c49060' })
hi(0, '@string.special', { link = 'SpecialChar' })
hi(0, '@string.special.symbol', { fg = '#51a8b3' })
hi(0, '@string.special.url', { link = 'Underlined' })
hi(0, '@tag', { fg = '#bb70d2' })
hi(0, '@tag.attribute', { fg = '#dbb671' })
hi(0, '@tag.builtin', { link = 'Special' })
hi(0, '@tag.delimiter', { fg = '#bb70d2' })
hi(0, '@text', { fg = '#a7aab0' })
hi(0, '@text.diff.add', { fg = '#8fb573' })
hi(0, '@text.diff.delete', { fg = '#de5d68' })
hi(0, '@text.emphasis', { fg = '#a7aab0', italic = true })
hi(0, '@text.environment', { fg = '#a7aab0' })
hi(0, '@text.environment.name', { fg = '#a7aab0' })
hi(0, '@text.literal', { fg = '#8fb573' })
hi(0, '@text.math', { fg = '#a7aab0' })
hi(0, '@text.reference', { fg = '#57a5e5' })
hi(0, '@text.strike', { fg = '#a7aab0', strikethrough = true })
hi(0, '@text.strong', { bold = true, fg = '#a7aab0' })
hi(0, '@text.title', { bold = true, fg = '#c49060' })
hi(0, '@text.todo', { fg = '#de5d68', italic = true })
hi(0, '@text.todo.checked', { fg = '#8fb573', italic = true })
hi(0, '@text.todo.unchecked', { fg = '#de5d68', italic = true })
hi(0, '@text.underline', { fg = '#a7aab0', underline = true })
hi(0, '@text.uri', { fg = '#51a8b3', underline = true })
hi(0, '@type', { fg = '#dbb671' })
hi(0, '@type.builtin', { fg = '#c49060' })
hi(0, '@variable', { fg = '#a7aab0' })
hi(0, '@variable.builtin', { fg = '#de5d68' })
hi(0, '@variable.member', { fg = '#51a8b3' })
hi(0, '@variable.parameter', { fg = '#de5d68' })
hi(0, '@variable.parameter.builtin', { link = 'Special' })
hi(0, '@warning', { fg = '#a7aab0' })
hi(0, 'ALEErrorSign', { fg = '#de5d68' })
hi(0, 'ALEInfoSign', { fg = '#51a8b3' })
hi(0, 'ALEWarningSign', { fg = '#dbb671' })
hi(0, 'Added', { ctermfg = 10, fg = '#8fb573' })
hi(0, 'AerialArrayIcon', { fg = '#dbb671' })
hi(0, 'AerialBooleanIcon', { fg = '#c49060' })
hi(0, 'AerialClassIcon', { fg = '#dbb671' })
hi(0, 'AerialColorIcon', { fg = '#8fb573' })
hi(0, 'AerialConstantIcon', { fg = '#c49060' })
hi(0, 'AerialConstructorIcon', { fg = '#57a5e5' })
hi(0, 'AerialDefaultIcon', { fg = '#bb70d2' })
hi(0, 'AerialEnumIcon', { fg = '#bb70d2' })
hi(0, 'AerialEnumMemberIcon', { fg = '#dbb671' })
hi(0, 'AerialEventIcon', { fg = '#dbb671' })
hi(0, 'AerialFieldIcon', { fg = '#bb70d2' })
hi(0, 'AerialFileIcon', { fg = '#57a5e5' })
hi(0, 'AerialFolderIcon', { fg = '#c49060' })
hi(0, 'AerialFunctionIcon', { fg = '#57a5e5' })
hi(0, 'AerialInterfaceIcon', { fg = '#8fb573' })
hi(0, 'AerialKeyIcon', { fg = '#51a8b3' })
hi(0, 'AerialKeywordIcon', { fg = '#51a8b3' })
hi(0, 'AerialLine', { bg = '#35363b', bold = true, fg = '#bb70d2' })
hi(0, 'AerialMethodIcon', { fg = '#57a5e5' })
hi(0, 'AerialModuleIcon', { fg = '#c49060' })
hi(0, 'AerialNamespaceIcon', { fg = '#de5d68' })
hi(0, 'AerialNullIcon', { fg = '#5a5b5e' })
hi(0, 'AerialNumberIcon', { fg = '#c49060' })
hi(0, 'AerialObjectIcon', { fg = '#de5d68' })
hi(0, 'AerialOperatorIcon', { fg = '#de5d68' })
hi(0, 'AerialPackageIcon', { fg = '#dbb671' })
hi(0, 'AerialPropertyIcon', { fg = '#51a8b3' })
hi(0, 'AerialReferenceIcon', { fg = '#c49060' })
hi(0, 'AerialSnippetIcon', { fg = '#de5d68' })
hi(0, 'AerialStringIcon', { fg = '#8fb573' })
hi(0, 'AerialStructIcon', { fg = '#bb70d2' })
hi(0, 'AerialTextIcon', { fg = '#818387' })
hi(0, 'AerialTypeParameterIcon', { fg = '#de5d68' })
hi(0, 'AerialUnitIcon', { fg = '#8fb573' })
hi(0, 'AerialValueIcon', { fg = '#c49060' })
hi(0, 'AerialVariableIcon', { fg = '#bb70d2' })
hi(0, 'BlinkCmpDetail', { fg = '#818387' })
hi(0, 'BlinkCmpKind', { fg = '#bb70d2' })
hi(0, 'BlinkCmpKindArray', { fg = '#dbb671' })
hi(0, 'BlinkCmpKindBoolean', { fg = '#c49060' })
hi(0, 'BlinkCmpKindClass', { fg = '#dbb671' })
hi(0, 'BlinkCmpKindColor', { fg = '#8fb573' })
hi(0, 'BlinkCmpKindConstant', { fg = '#c49060' })
hi(0, 'BlinkCmpKindConstructor', { fg = '#57a5e5' })
hi(0, 'BlinkCmpKindDefault', { fg = '#bb70d2' })
hi(0, 'BlinkCmpKindEnum', { fg = '#bb70d2' })
hi(0, 'BlinkCmpKindEnumMember', { fg = '#dbb671' })
hi(0, 'BlinkCmpKindEvent', { fg = '#dbb671' })
hi(0, 'BlinkCmpKindField', { fg = '#bb70d2' })
hi(0, 'BlinkCmpKindFile', { fg = '#57a5e5' })
hi(0, 'BlinkCmpKindFolder', { fg = '#c49060' })
hi(0, 'BlinkCmpKindFunction', { fg = '#57a5e5' })
hi(0, 'BlinkCmpKindInterface', { fg = '#8fb573' })
hi(0, 'BlinkCmpKindKey', { fg = '#51a8b3' })
hi(0, 'BlinkCmpKindKeyword', { fg = '#51a8b3' })
hi(0, 'BlinkCmpKindMethod', { fg = '#57a5e5' })
hi(0, 'BlinkCmpKindModule', { fg = '#c49060' })
hi(0, 'BlinkCmpKindNamespace', { fg = '#de5d68' })
hi(0, 'BlinkCmpKindNull', { fg = '#5a5b5e' })
hi(0, 'BlinkCmpKindNumber', { fg = '#c49060' })
hi(0, 'BlinkCmpKindObject', { fg = '#de5d68' })
hi(0, 'BlinkCmpKindOperator', { fg = '#de5d68' })
hi(0, 'BlinkCmpKindPackage', { fg = '#dbb671' })
hi(0, 'BlinkCmpKindProperty', { fg = '#51a8b3' })
hi(0, 'BlinkCmpKindReference', { fg = '#c49060' })
hi(0, 'BlinkCmpKindSnippet', { fg = '#de5d68' })
hi(0, 'BlinkCmpKindString', { fg = '#8fb573' })
hi(0, 'BlinkCmpKindStruct', { fg = '#bb70d2' })
hi(0, 'BlinkCmpKindText', { fg = '#818387' })
hi(0, 'BlinkCmpKindTypeParameter', { fg = '#de5d68' })
hi(0, 'BlinkCmpKindUnit', { fg = '#8fb573' })
hi(0, 'BlinkCmpKindValue', { fg = '#c49060' })
hi(0, 'BlinkCmpKindVariable', { fg = '#bb70d2' })
hi(0, 'BlinkCmpLabel', { fg = '#a7aab0' })
hi(0, 'BlinkCmpLabelDeprecated', { fg = '#818387', strikethrough = true })
hi(0, 'BlinkCmpLabelMatch', { fg = '#51a8b3' })
hi(0, 'Boolean', { fg = '#c49060' })
hi(0, 'BufferCurrent', { bold = true })
hi(0, 'BufferCurrentMod', { bold = true, fg = '#c49060', italic = true })
hi(0, 'BufferCurrentSign', { fg = '#bb70d2' })
hi(0, 'BufferInactiveMod', { bg = '#2c2d31', fg = '#818387', italic = true })
hi(0, 'BufferVisible', { bg = '#232326', fg = '#818387' })
hi(0, 'BufferVisibleIndex', { bg = '#232326', fg = '#818387' })
hi(0, 'BufferVisibleMod', { bg = '#232326', fg = '#dbb671', italic = true })
hi(0, 'BufferVisibleSign', { bg = '#232326', fg = '#818387' })
hi(0, 'BufferVisibleTarget', { bg = '#232326', fg = '#818387' })
hi(0, 'Changed', { ctermfg = 14, fg = '#57a5e5' })
hi(0, 'Character', { fg = '#c49060' })
hi(0, 'CmpItemAbbr', { fg = '#a7aab0' })
hi(0, 'CmpItemAbbrDefault', { fg = '#a7aab0' })
hi(0, 'CmpItemAbbrDeprecated', { fg = '#818387', strikethrough = true })
hi(0, 'CmpItemAbbrDeprecatedDefault', { fg = '#5a5b5e' })
hi(0, 'CmpItemAbbrMatch', { fg = '#51a8b3' })
hi(0, 'CmpItemAbbrMatchDefault', { fg = '#a7aab0' })
hi(0, 'CmpItemAbbrMatchFuzzy', { fg = '#51a8b3', underline = true })
hi(0, 'CmpItemAbbrMatchFuzzyDefault', { fg = '#a7aab0' })
hi(0, 'CmpItemKind', { fg = '#bb70d2' })
hi(0, 'CmpItemKindArray', { fg = '#dbb671' })
hi(0, 'CmpItemKindBoolean', { fg = '#c49060' })
hi(0, 'CmpItemKindClass', { fg = '#dbb671' })
hi(0, 'CmpItemKindClassDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindColor', { fg = '#8fb573' })
hi(0, 'CmpItemKindColorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindConstant', { fg = '#c49060' })
hi(0, 'CmpItemKindConstantDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindConstructor', { fg = '#57a5e5' })
hi(0, 'CmpItemKindConstructorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindDefault', { fg = '#de5d68' })
hi(0, 'CmpItemKindEnum', { fg = '#bb70d2' })
hi(0, 'CmpItemKindEnumDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEnumMember', { fg = '#dbb671' })
hi(0, 'CmpItemKindEnumMemberDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEvent', { fg = '#dbb671' })
hi(0, 'CmpItemKindEventDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindField', { fg = '#bb70d2' })
hi(0, 'CmpItemKindFieldDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFile', { fg = '#57a5e5' })
hi(0, 'CmpItemKindFileDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFolder', { fg = '#c49060' })
hi(0, 'CmpItemKindFolderDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFunction', { fg = '#57a5e5' })
hi(0, 'CmpItemKindFunctionDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindInterface', { fg = '#8fb573' })
hi(0, 'CmpItemKindInterfaceDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindKey', { fg = '#51a8b3' })
hi(0, 'CmpItemKindKeyword', { fg = '#51a8b3' })
hi(0, 'CmpItemKindKeywordDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindMethod', { fg = '#57a5e5' })
hi(0, 'CmpItemKindMethodDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindModule', { fg = '#c49060' })
hi(0, 'CmpItemKindModuleDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindNamespace', { fg = '#de5d68' })
hi(0, 'CmpItemKindNull', { fg = '#5a5b5e' })
hi(0, 'CmpItemKindNumber', { fg = '#c49060' })
hi(0, 'CmpItemKindObject', { fg = '#de5d68' })
hi(0, 'CmpItemKindOperator', { fg = '#de5d68' })
hi(0, 'CmpItemKindOperatorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindPackage', { fg = '#dbb671' })
hi(0, 'CmpItemKindProperty', { fg = '#51a8b3' })
hi(0, 'CmpItemKindPropertyDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindReference', { fg = '#c49060' })
hi(0, 'CmpItemKindReferenceDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindSnippet', { fg = '#de5d68' })
hi(0, 'CmpItemKindSnippetDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindString', { fg = '#8fb573' })
hi(0, 'CmpItemKindStruct', { fg = '#bb70d2' })
hi(0, 'CmpItemKindStructDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindText', { fg = '#818387' })
hi(0, 'CmpItemKindTextDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindTypeParameter', { fg = '#de5d68' })
hi(0, 'CmpItemKindTypeParameterDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindUnit', { fg = '#8fb573' })
hi(0, 'CmpItemKindUnitDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindValue', { fg = '#c49060' })
hi(0, 'CmpItemKindValueDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindVariable', { fg = '#bb70d2' })
hi(0, 'CmpItemKindVariableDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemMenu', { fg = '#818387' })
hi(0, 'CmpItemMenuDefault', { fg = '#a7aab0' })
hi(0, 'CocErrorSign', { fg = '#de5d68' })
hi(0, 'CocHintSign', { fg = '#bb70d2' })
hi(0, 'CocInfoSign', { fg = '#51a8b3' })
hi(0, 'CocWarningSign', { fg = '#dbb671' })
hi(0, 'ColorColumn', { bg = '#2c2d31' })
hi(0, 'Comment', { fg = '#5a5b5e', italic = true })
hi(0, 'Conceal', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'Conditional', { fg = '#bb70d2' })
hi(0, 'Constant', { fg = '#51a8b3' })
hi(0, 'CurSearch', { bg = '#c49060', ctermbg = 11, ctermfg = 0, fg = '#232326' })
hi(0, 'Cursor', { reverse = true })
hi(0, 'CursorColumn', { bg = '#2c2d31' })
hi(0, 'CursorIM', { reverse = true })
hi(0, 'CursorLine', { bg = '#2c2d31' })
hi(0, 'CursorLineNr', { fg = '#a7aab0' })
hi(0, 'DashboardCenter', { fg = '#51a8b3' })
hi(0, 'DashboardFooter', { fg = '#833b3b', italic = true })
hi(0, 'DashboardHeader', { fg = '#dbb671' })
hi(0, 'DashboardShortCut', { fg = '#57a5e5' })
hi(0, 'Debug', { fg = '#dbb671' })
hi(0, 'Define', { fg = '#bb70d2' })
hi(0, 'Delimiter', { fg = '#818387' })
hi(0, 'DiagnosticError', { ctermfg = 9, fg = '#de5d68' })
hi(0, 'DiagnosticHint', { ctermfg = 12, fg = '#bb70d2' })
hi(0, 'DiagnosticInfo', { ctermfg = 14, fg = '#51a8b3' })
hi(0, 'DiagnosticUnderlineError', { sp = '#de5d68', undercurl = true })
hi(0, 'DiagnosticUnderlineHint', { sp = '#bb70d2', undercurl = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = '#57a5e5', undercurl = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = '#dbb671', undercurl = true })
hi(0, 'DiagnosticVirtualTextError', { bg = '#2d2528', fg = '#833b3b' })
hi(0, 'DiagnosticVirtualTextHint', { bg = '#2c2630', fg = '#79428a' })
hi(0, 'DiagnosticVirtualTextInfo', { bg = '#24292c', fg = '#2b5d63' })
hi(0, 'DiagnosticVirtualTextWarn', { bg = '#2c2925', fg = '#7c5c20' })
hi(0, 'DiagnosticWarn', { ctermfg = 11, fg = '#dbb671' })
hi(0, 'DiffAdd', { bg = '#282b26', ctermbg = 10, ctermfg = 0 })
hi(0, 'DiffAdded', { fg = '#8fb573' })
hi(0, 'DiffChange', { bg = '#1a2a37' })
hi(0, 'DiffChanged', { fg = '#57a5e5' })
hi(0, 'DiffDelete', { bg = '#2a2626', ctermfg = 9 })
hi(0, 'DiffDeleted', { fg = '#de5d68' })
hi(0, 'DiffFile', { fg = '#51a8b3' })
hi(0, 'DiffIndexLine', { fg = '#5a5b5e' })
hi(0, 'DiffRemoved', { fg = '#de5d68' })
hi(0, 'DiffText', { bg = '#2c485f', ctermbg = 14, ctermfg = 0 })
hi(0, 'DiffviewCursorLine', { bg = '#2c2d31' })
hi(0, 'DiffviewEndOfBuffer', { bg = '#232326', fg = '#232326' })
hi(0, 'DiffviewFilePanelCounter', { bold = true, fg = '#bb70d2' })
hi(0, 'DiffviewFilePanelDeletions', { fg = '#de5d68' })
hi(0, 'DiffviewFilePanelFileName', { fg = '#a7aab0' })
hi(0, 'DiffviewFilePanelInsertions', { fg = '#8fb573' })
hi(0, 'DiffviewFilePanelPath', { fg = '#5a5b5e' })
hi(0, 'DiffviewFilePanelRootPath', { fg = '#5a5b5e' })
hi(0, 'DiffviewFilePanelTitle', { bold = true, fg = '#57a5e5' })
hi(0, 'DiffviewNormal', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'DiffviewSignColumn', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'DiffviewStatusAdded', { fg = '#8fb573' })
hi(0, 'DiffviewStatusBroken', { fg = '#de5d68' })
hi(0, 'DiffviewStatusCopied', { fg = '#57a5e5' })
hi(0, 'DiffviewStatusDeleted', { fg = '#de5d68' })
hi(0, 'DiffviewStatusLine', { bg = '#35363b', fg = '#a7aab0' })
hi(0, 'DiffviewStatusLineNC', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'DiffviewStatusModified', { fg = '#57a5e5' })
hi(0, 'DiffviewStatusRenamed', { fg = '#57a5e5' })
hi(0, 'DiffviewStatusTypeChange', { fg = '#57a5e5' })
hi(0, 'DiffviewStatusUnknown', { fg = '#de5d68' })
hi(0, 'DiffviewStatusUnmerged', { fg = '#57a5e5' })
hi(0, 'DiffviewStatusUntracked', { fg = '#57a5e5' })
hi(0, 'Directory', { ctermfg = 14, fg = '#57a5e5' })
hi(0, 'EndOfBuffer', { bg = '#232326', fg = '#232326' })
hi(0, 'Error', { ctermbg = 9, ctermfg = 0, fg = '#bb70d2' })
hi(0, 'ErrorMsg', { bold = true, ctermfg = 9, fg = '#de5d68' })
hi(0, 'Exception', { fg = '#bb70d2' })
hi(0, 'Float', { fg = '#c49060' })
hi(0, 'FloatBorder', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'FocusedSymbol', { bg = '#35363b', bold = true, fg = '#bb70d2' })
hi(0, 'FoldColumn', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'Folded', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'Function', { ctermfg = 14, fg = '#57a5e5' })
hi(0, 'GitGutterAdd', { fg = '#8fb573' })
hi(0, 'GitGutterChange', { fg = '#57a5e5' })
hi(0, 'GitGutterDelete', { fg = '#de5d68' })
hi(0, 'GitSignsAdd', { fg = '#8fb573' })
hi(0, 'GitSignsAddLn', { fg = '#8fb573' })
hi(0, 'GitSignsAddNr', { fg = '#8fb573' })
hi(0, 'GitSignsChange', { fg = '#57a5e5' })
hi(0, 'GitSignsChangeLn', { fg = '#57a5e5' })
hi(0, 'GitSignsChangeNr', { fg = '#57a5e5' })
hi(0, 'GitSignsDelete', { fg = '#de5d68' })
hi(0, 'GitSignsDeleteLn', { fg = '#de5d68' })
hi(0, 'GitSignsDeleteNr', { fg = '#de5d68' })
hi(0, 'HopNextKey', { bold = true, fg = '#de5d68' })
hi(0, 'HopNextKey1', { bold = true, fg = '#51a8b3' })
hi(0, 'HopNextKey2', { fg = '#3d73a0' })
hi(0, 'HopUnmatched', { fg = '#5a5b5e' })
hi(0, 'IblIndent', { fg = '#2c2d31', nocombine = true })
hi(0, 'IblScope', { fg = '#5a5b5e', nocombine = true })
hi(0, 'IblWhitespace', { fg = '#5a5b5e', nocombine = true })
hi(0, 'Identifier', { ctermfg = 12, fg = '#de5d68' })
hi(0, 'IlluminatedWordRead', { bg = '#35363b', bold = true })
hi(0, 'IlluminatedWordText', { bg = '#35363b', bold = true })
hi(0, 'IlluminatedWordWrite', { bg = '#35363b', bold = true })
hi(0, 'IncSearch', { bg = '#c49060', fg = '#232326' })
hi(0, 'Include', { fg = '#bb70d2' })
hi(0, 'IndentBlanklineChar', { fg = '#2c2d31', nocombine = true })
hi(0, 'IndentBlanklineContextChar', { fg = '#5a5b5e', nocombine = true })
hi(0, 'IndentBlanklineContextSpaceChar', { nocombine = true })
hi(0, 'IndentBlanklineContextStart', { sp = '#5a5b5e', underline = true })
hi(0, 'IndentBlanklineIndent1', { fg = '#57a5e5' })
hi(0, 'IndentBlanklineIndent2', { fg = '#8fb573' })
hi(0, 'IndentBlanklineIndent3', { fg = '#51a8b3' })
hi(0, 'IndentBlanklineIndent4', { fg = '#818387' })
hi(0, 'IndentBlanklineIndent5', { fg = '#bb70d2' })
hi(0, 'IndentBlanklineIndent6', { fg = '#de5d68' })
hi(0, 'Keyword', { fg = '#bb70d2' })
hi(0, 'Label', { fg = '#bb70d2' })
hi(0, 'LineNr', { fg = '#5a5b5e' })
hi(0, 'LspCodeLens', { fg = '#5a5b5e', italic = true })
hi(0, 'LspCodeLensSeparator', { fg = '#5a5b5e' })
hi(0, 'LspCxxHlGroupEnumConstant', { fg = '#c49060' })
hi(0, 'LspCxxHlGroupMemberVariable', { fg = '#c49060' })
hi(0, 'LspCxxHlGroupNamespace', { fg = '#57a5e5' })
hi(0, 'LspCxxHlSkippedRegion', { fg = '#5a5b5e' })
hi(0, 'LspCxxHlSkippedRegionBeginEnd', { fg = '#de5d68' })
hi(0, 'LspDiagnosticsDefaultError', { fg = '#de5d68' })
hi(0, 'LspDiagnosticsDefaultHint', { fg = '#bb70d2' })
hi(0, 'LspDiagnosticsDefaultInformation', { fg = '#51a8b3' })
hi(0, 'LspDiagnosticsDefaultWarning', { fg = '#dbb671' })
hi(0, 'LspDiagnosticsUnderlineError', { sp = '#de5d68', undercurl = true })
hi(0, 'LspDiagnosticsUnderlineHint', { sp = '#bb70d2', undercurl = true })
hi(0, 'LspDiagnosticsUnderlineInformation', { sp = '#57a5e5', undercurl = true })
hi(0, 'LspDiagnosticsUnderlineWarning', { sp = '#dbb671', undercurl = true })
hi(0, 'LspDiagnosticsVirtualTextError', { bg = '#2d2528', fg = '#833b3b' })
hi(0, 'LspDiagnosticsVirtualTextHint', { bg = '#2c2630', fg = '#79428a' })
hi(0, 'LspDiagnosticsVirtualTextInformation', { bg = '#24292c', fg = '#2b5d63' })
hi(0, 'LspDiagnosticsVirtualTextWarning', { bg = '#2c2925', fg = '#7c5c20' })
hi(0, 'LspReferenceRead', { bg = '#35363b' })
hi(0, 'LspReferenceText', { bg = '#35363b' })
hi(0, 'LspReferenceWrite', { bg = '#35363b' })
hi(0, 'Macro', { fg = '#de5d68' })
hi(0, 'MatchParen', { bg = '#5a5b5e' })
hi(0, 'MiniAnimateCursor', { nocombine = true, reverse = true })
hi(0, 'MiniAnimateNormalFloat', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniClueBorder', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'MiniClueDescGroup', { fg = '#dbb671' })
hi(0, 'MiniClueDescSingle', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniClueNextKey', { fg = '#bb70d2' })
hi(0, 'MiniClueNextKeyWithPostkeys', { fg = '#de5d68' })
hi(0, 'MiniClueSeparator', { fg = '#51a8b3' })
hi(0, 'MiniClueTitle', { fg = '#51a8b3' })
hi(0, 'MiniCompletionActiveParameter', { underline = true })
hi(0, 'MiniCursorword', { underline = true })
hi(0, 'MiniCursorwordCurrent', { underline = true })
hi(0, 'MiniDepsChangeAdded', { fg = '#8fb573' })
hi(0, 'MiniDepsChangeRemoved', { fg = '#de5d68' })
hi(0, 'MiniDepsHint', { fg = '#bb70d2' })
hi(0, 'MiniDepsInfo', { fg = '#51a8b3' })
hi(0, 'MiniDepsMsgBreaking', { fg = '#dbb671' })
hi(0, 'MiniDepsPlaceholder', { fg = '#5a5b5e', italic = true })
hi(0, 'MiniDepsTitle', { fg = '#51a8b3' })
hi(0, 'MiniDepsTitleError', { bg = '#2a2626' })
hi(0, 'MiniDepsTitleSame', { bg = '#2c485f' })
hi(0, 'MiniDepsTitleUpdate', { bg = '#282b26' })
hi(0, 'MiniDiffOverAdd', { bg = '#282b26' })
hi(0, 'MiniDiffOverChange', { bg = '#2c485f' })
hi(0, 'MiniDiffOverContext', { bg = '#1a2a37' })
hi(0, 'MiniDiffOverDelete', { bg = '#2a2626' })
hi(0, 'MiniDiffSignAdd', { fg = '#8fb573' })
hi(0, 'MiniDiffSignChange', { fg = '#57a5e5' })
hi(0, 'MiniDiffSignDelete', { fg = '#de5d68' })
hi(0, 'MiniFilesBorder', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'MiniFilesBorderModified', { fg = '#dbb671' })
hi(0, 'MiniFilesCursorLine', { bg = '#35363b' })
hi(0, 'MiniFilesDirectory', { fg = '#57a5e5' })
hi(0, 'MiniFilesFile', { fg = '#a7aab0' })
hi(0, 'MiniFilesNormal', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniFilesTitle', { fg = '#51a8b3' })
hi(0, 'MiniFilesTitleFocused', { bold = true, fg = '#51a8b3' })
hi(0, 'MiniHipatternsFixme', { bg = '#de5d68', bold = true, fg = '#232326' })
hi(0, 'MiniHipatternsHack', { bg = '#dbb671', bold = true, fg = '#232326' })
hi(0, 'MiniHipatternsNote', { bg = '#51a8b3', bold = true, fg = '#232326' })
hi(0, 'MiniHipatternsTodo', { bg = '#bb70d2', bold = true, fg = '#232326' })
hi(0, 'MiniIconsAzure', { fg = '#68aee8' })
hi(0, 'MiniIconsBlue', { fg = '#57a5e5' })
hi(0, 'MiniIconsCyan', { fg = '#51a8b3' })
hi(0, 'MiniIconsGreen', { fg = '#8fb573' })
hi(0, 'MiniIconsGrey', { fg = '#a7aab0' })
hi(0, 'MiniIconsOrange', { fg = '#c49060' })
hi(0, 'MiniIconsPurple', { fg = '#bb70d2' })
hi(0, 'MiniIconsRed', { fg = '#de5d68' })
hi(0, 'MiniIconsYellow', { fg = '#dbb671' })
hi(0, 'MiniIndentscopePrefix', { nocombine = true })
hi(0, 'MiniIndentscopeSymbol', { fg = '#5a5b5e' })
hi(0, 'MiniJump', { fg = '#bb70d2', sp = '#bb70d2', underline = true })
hi(0, 'MiniJump2dDim', { fg = '#5a5b5e', nocombine = true })
hi(0, 'MiniJump2dSpot', { bold = true, fg = '#de5d68', nocombine = true })
hi(0, 'MiniJump2dSpotAhead', { bg = '#232326', fg = '#51a8b3', nocombine = true })
hi(0, 'MiniJump2dSpotUnique', { bold = true, fg = '#dbb671', nocombine = true })
hi(0, 'MiniMapNormal', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniMapSymbolCount', { fg = '#de5d68' })
hi(0, 'MiniMapSymbolLine', { fg = '#51a8b3' })
hi(0, 'MiniMapSymbolView', { fg = '#818387' })
hi(0, 'MiniNotifyBorder', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'MiniNotifyNormal', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniNotifyTitle', { fg = '#51a8b3' })
hi(0, 'MiniOperatorsExchangeFrom', { bg = '#c49060', fg = '#232326' })
hi(0, 'MiniPickBorder', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'MiniPickBorderBusy', { fg = '#dbb671' })
hi(0, 'MiniPickBorderText', { bold = true, fg = '#51a8b3' })
hi(0, 'MiniPickHeader', { fg = '#bb70d2' })
hi(0, 'MiniPickIconDirectory', { fg = '#57a5e5' })
hi(0, 'MiniPickIconFile', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniPickMatchCurrent', { bg = '#35363b' })
hi(0, 'MiniPickMatchMarked', { bg = '#2c485f' })
hi(0, 'MiniPickMatchRanges', { fg = '#bb70d2' })
hi(0, 'MiniPickNormal', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniPickPreviewLine', { bg = '#35363b' })
hi(0, 'MiniPickPreviewRegion', { bg = '#c49060', fg = '#232326' })
hi(0, 'MiniPickPrompt', { fg = '#51a8b3' })
hi(0, 'MiniStarterCurrent', { nocombine = true })
hi(0, 'MiniStarterFooter', { fg = '#833b3b', italic = true })
hi(0, 'MiniStarterHeader', { fg = '#dbb671' })
hi(0, 'MiniStarterInactive', { fg = '#5a5b5e', italic = true })
hi(0, 'MiniStarterItem', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'MiniStarterItemBullet', { fg = '#5a5b5e' })
hi(0, 'MiniStarterItemPrefix', { fg = '#dbb671' })
hi(0, 'MiniStarterQuery', { fg = '#51a8b3' })
hi(0, 'MiniStarterSection', { fg = '#818387' })
hi(0, 'MiniStatuslineDevinfo', { bg = '#35363b', fg = '#a7aab0' })
hi(0, 'MiniStatuslineFileinfo', { bg = '#35363b', fg = '#a7aab0' })
hi(0, 'MiniStatuslineFilename', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'MiniStatuslineInactive', { bg = '#232326', fg = '#5a5b5e' })
hi(0, 'MiniStatuslineModeCommand', { bg = '#dbb671', bold = true, fg = '#232326' })
hi(0, 'MiniStatuslineModeInsert', { bg = '#57a5e5', bold = true, fg = '#232326' })
hi(0, 'MiniStatuslineModeNormal', { bg = '#8fb573', bold = true, fg = '#232326' })
hi(0, 'MiniStatuslineModeOther', { bg = '#51a8b3', bold = true, fg = '#232326' })
hi(0, 'MiniStatuslineModeReplace', { bg = '#de5d68', bold = true, fg = '#232326' })
hi(0, 'MiniStatuslineModeVisual', { bg = '#bb70d2', bold = true, fg = '#232326' })
hi(0, 'MiniSurround', { bg = '#c49060', fg = '#232326' })
hi(0, 'MiniTablineCurrent', { bold = true })
hi(0, 'MiniTablineFill', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'MiniTablineHidden', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'MiniTablineModifiedCurrent', { bold = true, fg = '#c49060', italic = true })
hi(0, 'MiniTablineModifiedHidden', { bg = '#2c2d31', fg = '#818387', italic = true })
hi(0, 'MiniTablineModifiedVisible', { bg = '#232326', fg = '#dbb671', italic = true })
hi(0, 'MiniTablineTabpagesection', { bg = '#e2c792', fg = '#232326' })
hi(0, 'MiniTablineVisible', { bg = '#232326', fg = '#818387' })
hi(0, 'MiniTestEmphasis', { bold = true })
hi(0, 'MiniTestFail', { bold = true, fg = '#de5d68' })
hi(0, 'MiniTestPass', { bold = true, fg = '#8fb573' })
hi(0, 'MiniTrailspace', { bg = '#de5d68' })
hi(0, 'MoreMsg', { bold = true, ctermfg = 14, fg = '#57a5e5' })
hi(0, 'MultiCursorCursor', { reverse = true })
hi(0, 'MultiCursorDisabledCursor', { reverse = true })
hi(0, 'NavicIconsArray', { fg = '#dbb671' })
hi(0, 'NavicIconsBoolean', { fg = '#c49060' })
hi(0, 'NavicIconsClass', { fg = '#dbb671' })
hi(0, 'NavicIconsColor', { fg = '#8fb573' })
hi(0, 'NavicIconsConstant', { fg = '#c49060' })
hi(0, 'NavicIconsConstructor', { fg = '#57a5e5' })
hi(0, 'NavicIconsDefault', { fg = '#bb70d2' })
hi(0, 'NavicIconsEnum', { fg = '#bb70d2' })
hi(0, 'NavicIconsEnumMember', { fg = '#dbb671' })
hi(0, 'NavicIconsEvent', { fg = '#dbb671' })
hi(0, 'NavicIconsField', { fg = '#bb70d2' })
hi(0, 'NavicIconsFile', { fg = '#57a5e5' })
hi(0, 'NavicIconsFolder', { fg = '#c49060' })
hi(0, 'NavicIconsFunction', { fg = '#57a5e5' })
hi(0, 'NavicIconsInterface', { fg = '#8fb573' })
hi(0, 'NavicIconsKey', { fg = '#51a8b3' })
hi(0, 'NavicIconsKeyword', { fg = '#51a8b3' })
hi(0, 'NavicIconsMethod', { fg = '#57a5e5' })
hi(0, 'NavicIconsModule', { fg = '#c49060' })
hi(0, 'NavicIconsNamespace', { fg = '#de5d68' })
hi(0, 'NavicIconsNull', { fg = '#5a5b5e' })
hi(0, 'NavicIconsNumber', { fg = '#c49060' })
hi(0, 'NavicIconsObject', { fg = '#de5d68' })
hi(0, 'NavicIconsOperator', { fg = '#de5d68' })
hi(0, 'NavicIconsPackage', { fg = '#dbb671' })
hi(0, 'NavicIconsProperty', { fg = '#51a8b3' })
hi(0, 'NavicIconsReference', { fg = '#c49060' })
hi(0, 'NavicIconsSnippet', { fg = '#de5d68' })
hi(0, 'NavicIconsString', { fg = '#8fb573' })
hi(0, 'NavicIconsStruct', { fg = '#bb70d2' })
hi(0, 'NavicIconsText', { fg = '#818387' })
hi(0, 'NavicIconsTypeParameter', { fg = '#de5d68' })
hi(0, 'NavicIconsUnit', { fg = '#8fb573' })
hi(0, 'NavicIconsValue', { fg = '#c49060' })
hi(0, 'NavicIconsVariable', { fg = '#bb70d2' })
hi(0, 'NavicSeparator', { fg = '#818387' })
hi(0, 'NavicText', { fg = '#a7aab0' })
hi(0, 'NeoTreeEndOfBuffer', { bg = '#1b1c1e', fg = '#1b1c1e' })
hi(0, 'NeoTreeGitAdded', { fg = '#8fb573' })
hi(0, 'NeoTreeGitConflict', { bold = true, fg = '#de5d68', italic = true })
hi(0, 'NeoTreeGitDeleted', { fg = '#de5d68' })
hi(0, 'NeoTreeGitModified', { fg = '#dbb671' })
hi(0, 'NeoTreeGitUntracked', { fg = '#de5d68', italic = true })
hi(0, 'NeoTreeIndentMarker', { fg = '#5a5b5e' })
hi(0, 'NeoTreeNormal', { bg = '#1b1c1e', fg = '#a7aab0' })
hi(0, 'NeoTreeNormalNC', { bg = '#1b1c1e', fg = '#a7aab0' })
hi(0, 'NeoTreeRootName', { bold = true, fg = '#c49060' })
hi(0, 'NeoTreeSymbolicLinkTarget', { fg = '#bb70d2' })
hi(0, 'NeoTreeVertSplit', { bg = '#2c2d31', fg = '#2c2d31' })
hi(0, 'NeoTreeWinSeparator', { bg = '#2c2d31', fg = '#2c2d31' })
hi(0, 'NeotestAdapterName', { bold = true, fg = '#bb70d2' })
hi(0, 'NeotestDir', { fg = '#51a8b3' })
hi(0, 'NeotestExpandMarker', { fg = '#5a5b5e' })
hi(0, 'NeotestFailed', { fg = '#de5d68' })
hi(0, 'NeotestFile', { fg = '#51a8b3' })
hi(0, 'NeotestFocused', { bold = true, italic = true })
hi(0, 'NeotestIndent', { fg = '#5a5b5e' })
hi(0, 'NeotestMarked', { bold = true, fg = '#c49060' })
hi(0, 'NeotestNamespace', { fg = '#57a5e5' })
hi(0, 'NeotestPassed', { fg = '#8fb573' })
hi(0, 'NeotestRunning', { fg = '#dbb671' })
hi(0, 'NeotestSkipped', { fg = '#818387' })
hi(0, 'NeotestTarget', { fg = '#bb70d2' })
hi(0, 'NeotestTest', { fg = '#a7aab0' })
hi(0, 'NeotestUnknown', { fg = '#818387' })
hi(0, 'NeotestWinSelect', { bold = true, fg = '#51a8b3' })
hi(0, 'NonText', { fg = '#5a5b5e' })
hi(0, 'Normal', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'NormalFloat', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'Number', { fg = '#c49060' })
hi(0, 'NvimTreeEndOfBuffer', { bg = '#1b1c1e', fg = '#1b1c1e' })
hi(0, 'NvimTreeFolderName', { fg = '#57a5e5' })
hi(0, 'NvimTreeGitDeleted', { fg = '#de5d68' })
hi(0, 'NvimTreeGitDirty', { fg = '#dbb671' })
hi(0, 'NvimTreeGitNew', { fg = '#8fb573' })
hi(0, 'NvimTreeImageFile', { fg = '#79428a' })
hi(0, 'NvimTreeIndentMarker', { fg = '#a7aab0' })
hi(0, 'NvimTreeNormal', { bg = '#1b1c1e', fg = '#a7aab0' })
hi(0, 'NvimTreeNormalFloat', { bg = '#1b1c1e', fg = '#a7aab0' })
hi(0, 'NvimTreeRootFolder', { bold = true, fg = '#c49060' })
hi(0, 'NvimTreeSpecialFile', { fg = '#dbb671', underline = true })
hi(0, 'NvimTreeSymlink', { fg = '#bb70d2' })
hi(0, 'NvimTreeVertSplit', { bg = '#1b1c1e', fg = '#1b1c1e' })
hi(0, 'Operator', { fg = '#bb70d2' })
hi(0, 'Pmenu', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'PmenuSbar', { bg = '#2c2d31' })
hi(0, 'PmenuSel', { bg = '#68aee8', blend = 0, fg = '#232326' })
hi(0, 'PmenuThumb', { bg = '#5a5b5e' })
hi(0, 'PreCondit', { fg = '#bb70d2' })
hi(0, 'PreProc', { fg = '#bb70d2' })
hi(0, 'Question', { ctermfg = 14, fg = '#dbb671' })
hi(0, 'QuickFixLine', { ctermfg = 14, fg = '#57a5e5', underline = true })
hi(0, 'RainbowDelimiterBlue', { fg = '#57a5e5' })
hi(0, 'RainbowDelimiterCyan', { fg = '#51a8b3' })
hi(0, 'RainbowDelimiterGreen', { fg = '#8fb573' })
hi(0, 'RainbowDelimiterOrange', { fg = '#c49060' })
hi(0, 'RainbowDelimiterRed', { fg = '#de5d68' })
hi(0, 'RainbowDelimiterViolet', { fg = '#bb70d2' })
hi(0, 'RainbowDelimiterYellow', { fg = '#dbb671' })
hi(0, 'Removed', { ctermfg = 9, fg = '#de5d68' })
hi(0, 'Repeat', { fg = '#bb70d2' })
hi(0, 'Search', { bg = '#e2c792', ctermbg = 11, ctermfg = 0, fg = '#232326' })
hi(0, 'SignColumn', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'SnacksDashboardDesc', { fg = '#51a8b3' })
hi(0, 'SnacksDashboardFooter', { fg = '#833b3b', italic = true })
hi(0, 'SnacksDashboardHeader', { fg = '#dbb671' })
hi(0, 'SnacksDashboardIcon', { fg = '#51a8b3' })
hi(0, 'SnacksDashboardKey', { fg = '#57a5e5' })
hi(0, 'SnacksDashboardSpecial', { bold = true, fg = '#833b3b' })
hi(0, 'SnacksPicker', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'SnacksPickerBorder', { fg = '#51a8b3' })
hi(0, 'SnacksPickerMatch', { bold = true, fg = '#c49060' })
hi(0, 'SnacksPickerTitle', { fg = '#de5d68' })
hi(0, 'Special', { ctermfg = 14, fg = '#de5d68' })
hi(0, 'SpecialChar', { fg = '#de5d68' })
hi(0, 'SpecialComment', { fg = '#5a5b5e', italic = true })
hi(0, 'SpecialKey', { fg = '#5a5b5e' })
hi(0, 'SpellBad', { sp = '#de5d68', undercurl = true })
hi(0, 'SpellCap', { sp = '#dbb671', undercurl = true })
hi(0, 'SpellLocal', { sp = '#57a5e5', undercurl = true })
hi(0, 'SpellRare', { sp = '#bb70d2', undercurl = true })
hi(0, 'Statement', { fg = '#bb70d2' })
hi(0, 'StatusLine', { bg = '#35363b', fg = '#a7aab0' })
hi(0, 'StatusLineNC', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'StatusLineTerm', { bg = '#35363b', fg = '#a7aab0' })
hi(0, 'StatusLineTermNC', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'StorageClass', { fg = '#dbb671' })
hi(0, 'String', { ctermfg = 10, fg = '#8fb573' })
hi(0, 'Structure', { fg = '#dbb671' })
hi(0, 'Substitute', { bg = '#8fb573', fg = '#232326' })
hi(0, 'TSRainbowBlue', { fg = '#57a5e5' })
hi(0, 'TSRainbowCyan', { fg = '#51a8b3' })
hi(0, 'TSRainbowGreen', { fg = '#8fb573' })
hi(0, 'TSRainbowOrange', { fg = '#c49060' })
hi(0, 'TSRainbowRed', { fg = '#de5d68' })
hi(0, 'TSRainbowViolet', { fg = '#bb70d2' })
hi(0, 'TSRainbowYellow', { fg = '#dbb671' })
hi(0, 'TabLine', { bg = '#2c2d31', fg = '#a7aab0' })
hi(0, 'TabLineFill', { bg = '#2c2d31', fg = '#5a5b5e' })
hi(0, 'TabLineSel', { bg = '#a7aab0', fg = '#232326' })
hi(0, 'Tag', { fg = '#8fb573' })
hi(0, 'TelescopeBorder', { fg = '#de5d68' })
hi(0, 'TelescopeMatching', { bold = true, fg = '#c49060' })
hi(0, 'TelescopePreviewBorder', { fg = '#51a8b3' })
hi(0, 'TelescopePromptBorder', { fg = '#51a8b3' })
hi(0, 'TelescopePromptPrefix', { fg = '#8fb573' })
hi(0, 'TelescopeResultsBorder', { fg = '#51a8b3' })
hi(0, 'TelescopeSelection', { bg = '#35363b' })
hi(0, 'TelescopeSelectionCaret', { fg = '#dbb671' })
hi(0, 'Terminal', { bg = '#232326', fg = '#a7aab0' })
hi(0, 'Title', { fg = '#51a8b3' })
hi(0, 'Todo', { fg = '#de5d68', italic = true })
hi(0, 'ToolbarButton', { bg = '#68aee8', fg = '#232326' })
hi(0, 'ToolbarLine', { fg = '#a7aab0' })
hi(0, 'Type', { fg = '#dbb671' })
hi(0, 'Typedef', { fg = '#dbb671' })
hi(0, 'Visual', { bg = '#37383d', ctermbg = 15, ctermfg = 0 })
hi(0, 'VisualNOS', { bg = '#35363b', underline = true })
hi(0, 'WarningMsg', { bold = true, ctermfg = 11, fg = '#dbb671' })
hi(0, 'WhichKey', { fg = '#de5d68' })
hi(0, 'WhichKeyDesc', { fg = '#57a5e5' })
hi(0, 'WhichKeyGroup', { fg = '#c49060' })
hi(0, 'WhichKeySeparator', { fg = '#8fb573' })
hi(0, 'Whitespace', { fg = '#5a5b5e' })
hi(0, 'WildMenu', { bg = '#57a5e5', fg = '#232326' })
hi(0, 'WinSeparator', { fg = '#37383d' })
hi(0, 'ZenBg', { bg = '#212124', fg = '#212124' })
hi(0, 'cDefine', { fg = '#51a8b3' })
hi(0, 'cInclude', { fg = '#57a5e5' })
hi(0, 'cStorageClass', { fg = '#bb70d2' })
hi(0, 'cTSConstMacro', { fg = '#bb70d2' })
hi(0, 'cTSConstant', { fg = '#51a8b3' })
hi(0, 'cTSInclude', { fg = '#57a5e5' })
hi(0, 'cTSOperator', { fg = '#bb70d2' })
hi(0, 'cTypedef', { fg = '#bb70d2' })
hi(0, 'cppStatement', { bold = true, fg = '#bb70d2' })
hi(0, 'cppTSConstMacro', { fg = '#bb70d2' })
hi(0, 'cppTSConstant', { fg = '#51a8b3' })
hi(0, 'cppTSInclude', { fg = '#57a5e5' })
hi(0, 'cppTSOperator', { fg = '#bb70d2' })
hi(0, 'debugBreakpoint', { bg = '#de5d68', fg = '#232326' })
hi(0, 'debugPC', { bg = '#8fb573', fg = '#232326' })
hi(0, 'iCursor', { reverse = true })
hi(0, 'illuminatedCurWord', { bg = '#35363b', bold = true })
hi(0, 'illuminatedWord', { bg = '#35363b', bold = true })
hi(0, 'lCursor', { reverse = true })
hi(0, 'latexTSEnvironment', { bold = true, fg = '#51a8b3' })
hi(0, 'latexTSEnvironmentName', { fg = '#dbb671' })
hi(0, 'latexTSFuncMacro', { fg = '#a7aab0' })
hi(0, 'latexTSInclude', { fg = '#57a5e5' })
hi(0, 'latexTSMath', { fg = '#c49060' })
hi(0, 'latexTSTitle', { fg = '#8fb573' })
hi(0, 'latexTSType', { fg = '#57a5e5' })
hi(0, 'markdownBlockquote', { fg = '#5a5b5e' })
hi(0, 'markdownBold', { bold = true })
hi(0, 'markdownBoldDelimiter', { fg = '#5a5b5e' })
hi(0, 'markdownCode', { fg = '#8fb573' })
hi(0, 'markdownCodeBlock', { fg = '#8fb573' })
hi(0, 'markdownCodeDelimiter', { fg = '#dbb671' })
hi(0, 'markdownH1', { bold = true, fg = '#de5d68' })
hi(0, 'markdownH2', { bold = true, fg = '#bb70d2' })
hi(0, 'markdownH3', { bold = true, fg = '#c49060' })
hi(0, 'markdownH4', { bold = true, fg = '#de5d68' })
hi(0, 'markdownH5', { bold = true, fg = '#bb70d2' })
hi(0, 'markdownH6', { bold = true, fg = '#c49060' })
hi(0, 'markdownHeadingDelimiter', { fg = '#5a5b5e' })
hi(0, 'markdownHeadingRule', { fg = '#5a5b5e' })
hi(0, 'markdownId', { fg = '#dbb671' })
hi(0, 'markdownIdDeclaration', { fg = '#de5d68' })
hi(0, 'markdownItalic', { italic = true })
hi(0, 'markdownItalicDelimiter', { fg = '#5a5b5e', italic = true })
hi(0, 'markdownLinkDelimiter', { fg = '#5a5b5e' })
hi(0, 'markdownLinkText', { fg = '#de5d68' })
hi(0, 'markdownLinkTextDelimiter', { fg = '#5a5b5e' })
hi(0, 'markdownListMarker', { fg = '#de5d68' })
hi(0, 'markdownOrderedListMarker', { fg = '#de5d68' })
hi(0, 'markdownRule', { fg = '#bb70d2' })
hi(0, 'markdownUrl', { fg = '#57a5e5', underline = true })
hi(0, 'markdownUrlDelimiter', { fg = '#5a5b5e' })
hi(0, 'markdownUrlTitleDelimiter', { fg = '#8fb573' })
hi(0, 'phpBoolean', { fg = '#51a8b3' })
hi(0, 'phpFCKeyword', { fg = '#bb70d2' })
hi(0, 'phpFunctions', { fg = '#a7aab0' })
hi(0, 'phpHereDoc', { fg = '#8fb573' })
hi(0, 'phpIdentifier', { fg = '#c49060' })
hi(0, 'phpMemberSelector', { fg = '#a7aab0' })
hi(0, 'phpMethods', { fg = '#51a8b3' })
hi(0, 'phpNowDoc', { fg = '#8fb573' })
hi(0, 'phpNumber', { fg = '#c49060' })
hi(0, 'phpOperator', { fg = '#bb70d2' })
hi(0, 'phpRegion', { fg = '#57a5e5' })
hi(0, 'phpSCKeyword', { fg = '#bb70d2' })
hi(0, 'phpStructure', { fg = '#bb70d2' })
hi(0, 'phpVarSelector', { fg = '#c49060' })
hi(0, 'rainbowcol1', { fg = '#818387' })
hi(0, 'rainbowcol2', { fg = '#dbb671' })
hi(0, 'rainbowcol3', { fg = '#57a5e5' })
hi(0, 'rainbowcol4', { fg = '#c49060' })
hi(0, 'rainbowcol5', { fg = '#bb70d2' })
hi(0, 'rainbowcol6', { fg = '#8fb573' })
hi(0, 'rainbowcol7', { fg = '#de5d68' })
hi(0, 'scalaInterpolation', { fg = '#bb70d2' })
hi(0, 'scalaInterpolationBoundary', { fg = '#bb70d2' })
hi(0, 'scalaKeywordModifier', { fg = '#de5d68' })
hi(0, 'scalaNameDefinition', { fg = '#a7aab0' })
hi(0, 'scalaOperator', { fg = '#de5d68' })
hi(0, 'scalaTypeOperator', { fg = '#de5d68' })
hi(0, 'texCmd', { fg = '#bb70d2' })
hi(0, 'texCmdEnv', { fg = '#51a8b3' })
hi(0, 'texCmdPackage', { fg = '#57a5e5' })
hi(0, 'texCmdPart', { fg = '#57a5e5' })
hi(0, 'texEnvArgName', { fg = '#dbb671' })
hi(0, 'texMathDelim', { fg = '#bb70d2' })
hi(0, 'texMathDelimZone', { fg = '#818387' })
hi(0, 'texMathOper', { fg = '#de5d68' })
hi(0, 'texMathZoneX', { fg = '#c49060' })
hi(0, 'texMathZoneXX', { fg = '#c49060' })
hi(0, 'texPgfType', { fg = '#dbb671' })
hi(0, 'vCursor', { reverse = true })
hi(0, 'vimCommentTitle', { fg = '#818387', italic = true })
hi(0, 'vimMap', { fg = '#bb70d2' })
hi(0, 'vimMapLhs', { fg = '#a7aab0' })
hi(0, 'vimMapModKey', { fg = '#c49060' })
hi(0, 'vimMapRhs', { fg = '#57a5e5' })
hi(0, 'vimNotation', { fg = '#de5d68' })
hi(0, 'vimOption', { fg = '#de5d68' })
hi(0, 'vimSetEqual', { fg = '#dbb671' })
hi(0, 'vimVar', { fg = '#a7aab0' })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = '#101012'
g.terminal_color_1 = '#de5d68'
g.terminal_color_2 = '#8fb573'
g.terminal_color_3 = '#dbb671'
g.terminal_color_4 = '#57a5e5'
g.terminal_color_5 = '#bb70d2'
g.terminal_color_6 = '#51a8b3'
g.terminal_color_7 = '#a7aab0'
g.terminal_color_8 = '#5a5b5e'
g.terminal_color_9 = '#de5d68'
g.terminal_color_10 = '#8fb573'
g.terminal_color_11 = '#dbb671'
g.terminal_color_12 = '#57a5e5'
g.terminal_color_13 = '#bb70d2'
g.terminal_color_14 = '#51a8b3'
g.terminal_color_15 = '#a7aab0'
